# Generated by Django 3.2.9 on 2021-11-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
    ]
