# Generated by Django 3.2.9 on 2021-11-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
