# Generated by Django 3.2.9 on 2021-11-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(help_text='Nome do departamento', max_length=100),
        ),
    ]
