# Generated by Django 3.2.9 on 2021-11-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
